# Generated by Django 3.0.4 on 2020-10-21 00:18

import contrib.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254)),
                ('value', models.CharField(max_length=254)),
                ('type', models.IntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Boolean'), (4, 'Float'), (5, 'Object')])),
            ],
            bases=(contrib.mixin.Model, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Project name')),
                ('instance_uri', models.URLField(max_length=128, unique=True, verbose_name='Instance URI')),
                ('api_key', models.CharField(max_length=254, null=True)),
                ('api_secret', models.CharField(max_length=254, null=True)),
                ('instance_username', models.CharField(max_length=254, null=True)),
                ('instance_secret', models.CharField(max_length=254, null=True)),
            ],
            bases=(contrib.mixin.Model, models.Model),
        ),
        migrations.CreateModel(
            name='SkillStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=254)),
                ('package', models.CharField(max_length=254)),
                ('component', models.CharField(max_length=254, null=True)),
                ('category', models.TextField(max_length=128)),
                ('description', models.TextField()),
                ('state', models.IntegerField(choices=[(1, 'Draft'), (2, 'Validated'), (3, 'Waiting for approval'), (4, 'Approved'), (5, 'Published'), (6, 'Rejected'), (7, 'Removed')], default=1)),
                ('reject_reason', models.TextField(null=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
