# Generated by Django 3.0.4 on 2020-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keycloak_admin_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_admin_username',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_client_id',
            field=models.CharField(default='main', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_client_secret',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_project_user_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_realm_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_server_url',
            field=models.CharField(default='https://login.igotbot.com/auth/', max_length=128),
        ),
    ]
