# Generated by Django 3.0.4 on 2020-10-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201025_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='keycloak_admin_password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_admin_username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_client_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_client_secret',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_project_user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_realm_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keycloak_server_url',
        ),
    ]
