# Generated by Django 3.0.4 on 2020-10-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201025_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_user_id', models.CharField(max_length=128, verbose_name='Keycloak User ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InstanceUser_project_id', to='core.Project')),
            ],
        ),
    ]
