# Generated by Django 3.0.4 on 2020-10-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instanceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_user_id',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
