# Generated by Django 3.0.4 on 2020-12-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_customer_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakRealm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(max_length=128, unique=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keycloak_realm', to='core.Project')),
            ],
        ),
    ]
