# Generated by Django 3.0.4 on 2021-02-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201226_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycloakrealm',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='in_process',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keycloak_realm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='core.KeycloakRealm'),
        ),
        migrations.AlterField(
            model_name='keycloakrealm',
            name='admin',
            field=models.EmailField(blank=True, default='admin@igotbot.com', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(default='')),
                ('gitlab_pipeline', models.BigIntegerField(default=0)),
                ('host_production', models.CharField(max_length=100)),
                ('host_staging', models.CharField(max_length=100)),
                ('random_id', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Finished'), (3, 'Error'), (4, 'Canceled')], default=0)),
                ('step', models.IntegerField(choices=[(0, 'Keycloak'), (1, 'Gitlab'), (2, 'Setup'), (3, 'End')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='core.Project')),
            ],
        ),
    ]
