# Generated by Django 3.0.4 on 2021-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210202_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
