# Generated by Django 3.0.4 on 2021-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stack_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='gitlab_pipeline',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='host_production',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='host_staging',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='random_id',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='token',
        ),
        migrations.AddField(
            model_name='stack',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
