# Generated by Django 3.0.4 on 2021-02-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210215_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customer_user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KeycloakUser'),
        ),
        migrations.DeleteModel(
            name='InstanceUser',
        ),
    ]
