# Generated by Django 3.0.4 on 2021-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210223_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakrealm',
            name='public_key',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
